/** @jest-environment jsdom */
'use strict';

const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, '..', 'editor-qr-runtime.js'), 'utf8');

describe('editor QR runtime', () => {
  let generatedBlobs;

  beforeEach(() => {
    document.documentElement.lang = 'ar';
    document.body.innerHTML = `
      <input type="radio" name="qr-source" value="auto-card" checked>
      <input id="qr-use-logo" type="checkbox">
      <input id="qr-dots-color" value="#112233">
      <input id="qr-bg-color" value="#ffffff">
      <select id="qr-dots-type"><option value="rounded" selected>rounded</option></select>
      <select id="qr-corners-type"><option value="extra-rounded" selected>extra-rounded</option></select>
      <div id="qr-temp"></div>
    `;
    window.history.replaceState({}, '', '/nfc/editor.html');
    generatedBlobs = 0;

    global.Config = window.Config = {
      currentDesignId: 'design-existing',
      SCRIPT_URLS: {
        qrCodeStyling: 'https://unpkg.com/qr-code-styling.js',
        qrcode: 'https://cdnjs.cloudflare.com/qrcode.js'
      }
    };
    global.DOMElements = window.DOMElements = {
      buttons: { generateAutoQr: document.createElement('button') },
      draggable: { logoImg: { src: 'https://www.mcprim.com/nfc/mc-prime-nfc.png' } },
      qrCodeTempGenerator: document.getElementById('qr-temp')
    };
    global.CardManager = window.CardManager = {
      autoGeneratedQrDataUrl: null,
      qrCodeImageUrl: null,
      updateQrCodeDisplay: jest.fn()
    };
    global.StateManager = window.StateManager = {
      getStateObject: jest.fn(() => ({
        inputs: { 'qr-source': 'auto-card' },
        imageUrls: { qrCode: null }
      })),
      applyState: jest.fn(() => {
        CardManager.autoGeneratedQrDataUrl = null;
      }),
      save: jest.fn()
    };
    global.ShareManager = window.ShareManager = {
      saveDesign: jest.fn(async () => Config.currentDesignId)
    };
    global.Utils = window.Utils = { loadScript: jest.fn(async () => {}) };
    global.UIManager = window.UIManager = {
      setButtonLoadingState: jest.fn(),
      announce: jest.fn()
    };
    global.QRCodeStyling = window.QRCodeStyling = jest.fn().mockImplementation(options => ({
      options,
      append: jest.fn(),
      getRawData: jest.fn(async () => {
        generatedBlobs += 1;
        return new Blob(['qr-image'], { type: 'image/png' });
      })
    }));
    global.alert = window.alert = jest.fn();

    eval(source);
  });

  afterEach(() => {
    [
      'Config', 'DOMElements', 'CardManager', 'StateManager', 'ShareManager',
      'Utils', 'UIManager', 'QRCodeStyling', 'EditorQrRuntime', 'alert'
    ].forEach(key => {
      delete global[key];
      delete window[key];
    });
  });

  test('replaces external QR CDNs with same-origin assets', () => {
    expect(Config.SCRIPT_URLS.qrCodeStyling).toBe('/nfc/vendor/qr-code-styling.js?v=1.5.0');
    expect(Config.SCRIPT_URLS.qrcode).toBe('/nfc/vendor/qrcode.min.js?v=1.0.0');
  });

  test('generates and persists an automatic QR for an existing design with one request', async () => {
    const id = await CardManager.generateCardLinkQr();

    expect(id).toBe('design-existing');
    expect(Utils.loadScript).toHaveBeenCalledWith('/nfc/vendor/qr-code-styling.js?v=1.5.0');
    expect(ShareManager.saveDesign).toHaveBeenCalledTimes(1);
    expect(ShareManager.saveDesign.mock.calls[0][0].imageUrls.qrCode).toMatch(/^data:image\/png;base64,/);
    expect(CardManager.autoGeneratedQrDataUrl).toMatch(/^data:image\/png;base64,/);
    expect(CardManager.qrCodeImageUrl).toBe(CardManager.autoGeneratedQrDataUrl);
    expect(CardManager.updateQrCodeDisplay).toHaveBeenCalled();
    expect(StateManager.save).toHaveBeenCalled();
    expect(alert).not.toHaveBeenCalled();
  });

  test('uses a two-phase save only when a new design needs an id', async () => {
    Config.currentDesignId = null;
    ShareManager.saveDesign
      .mockImplementationOnce(async () => {
        Config.currentDesignId = 'design-new';
        return 'design-new';
      })
      .mockImplementationOnce(async state => {
        expect(state.imageUrls.qrCode).toMatch(/^data:image\/png;base64,/);
        return 'design-new';
      });

    await CardManager.generateCardLinkQr();

    expect(ShareManager.saveDesign).toHaveBeenCalledTimes(2);
    expect(ShareManager.saveDesign.mock.calls[0]).toEqual([]);
    expect(ShareManager.saveDesign.mock.calls[1][0].imageUrls.qrCode).toMatch(/^data:image\/png;base64,/);
  });

  test('deduplicates concurrent generation attempts', async () => {
    await Promise.all([
      CardManager.generateCardLinkQr(),
      CardManager.generateCardLinkQr(),
      CardManager.generateCardLinkQr()
    ]);

    expect(generatedBlobs).toBe(1);
    expect(ShareManager.saveDesign).toHaveBeenCalledTimes(1);
  });

  test('includes generated QR data in state and restores it when editing', () => {
    const savedQr = 'data:image/png;base64,c2F2ZWQ=';
    CardManager.autoGeneratedQrDataUrl = savedQr;

    expect(StateManager.getStateObject().imageUrls.qrCode).toBe(savedQr);

    StateManager.applyState({
      inputs: { 'qr-source': 'auto-card' },
      imageUrls: { qrCode: savedQr }
    });

    expect(CardManager.autoGeneratedQrDataUrl).toBe(savedQr);
    expect(CardManager.qrCodeImageUrl).toBe(savedQr);
    expect(CardManager.updateQrCodeDisplay).toHaveBeenCalled();
  });
});
