// script-card.js - النسخة الآمنة المحدثة
"use strict";

const DragManager = {
  init() {
    const draggableSelectors = [
      "#card-logo",
      "#card-personal-photo-wrapper",
      "#card-name",
      "#card-tagline",
      "#qr-code-wrapper",
    ];
    draggableSelectors.forEach((selector) => this.makeDraggable(selector));
    this.setupDropzones();
  },
  makeDraggable(selector) {
    interact(selector).draggable({
      inertia: true,
      modifiers: [
        interact.modifiers.restrictRect({
          restriction: "parent",
          endOnly: true,
        }),
      ],
      autoScroll: false,
      listeners: {
        start: this.dragStartListener,
        move: this.dragMoveListener,
        end: this.dragEndListener,
      },
    });
  },
  setupDropzones() {
    interact(".card-content-layer").dropzone({
      accept: ".draggable-on-card",
      overlap: 0.5,
      ondrop: (event) => {
        if (window.innerWidth <= 1200) return;

        const droppedElement = event.relatedTarget;
        const dropzone = event.target;
        const newPlacement =
          dropzone.id === "card-front-content" ? "front" : "back";

        const placementMap = {
          "card-logo": "logo",
          "card-personal-photo-wrapper": "photo",
          "card-name": "name",
          "card-tagline": "tagline",
          "qr-code-wrapper": "qr",
        };

        let controlName = placementMap[droppedElement.id];
        let radioToSelect;

        if (controlName) {
          radioToSelect = document.querySelector(
            `input[name="placement-${controlName}"][value="${newPlacement}"]`,
          );
        } else if (
          droppedElement.classList.contains("phone-button-draggable-wrapper")
        ) {
          const phoneId = droppedElement.id;
          radioToSelect = document.querySelector(
            `#phone-control-${phoneId} input[name="placement-${phoneId}"][value="${newPlacement}"]`,
          );
        } else if (droppedElement.classList.contains("draggable-social-link")) {
          const controlId = droppedElement.dataset.controlId;
          const controlElement = document.getElementById(controlId);
          if (controlElement) {
            const radioName = controlElement.querySelector(
              'input[type="radio"]',
            )?.name;
            if (radioName) {
              radioToSelect = controlElement.querySelector(
                `input[name="${radioName}"][value="${newPlacement}"]`,
              );
            }
          }
        }

        if (radioToSelect && !radioToSelect.checked) {
          radioToSelect.checked = true;

          droppedElement.style.transform = "translate(0px, 0px)";
          droppedElement.setAttribute("data-x", "0");
          droppedElement.setAttribute("data-y", "0");

          CardManager.renderCardContent();
        }
      },
      ondragenter: (event) => {
        if (window.innerWidth > 1200)
          event.target.classList.add("drop-target-active");
      },
      ondragleave: (event) =>
        event.target.classList.remove("drop-target-active"),
      ondropdeactivate: (event) =>
        event.target.classList.remove("drop-target-active"),
    });
  },
  dragStartListener(event) {
    event.target.classList.add("dragging");
  },
  dragMoveListener(event) {
    const target = event.target;
    const x = (parseFloat(target.getAttribute("data-x")) || 0) + event.dx;
    const y = (parseFloat(target.getAttribute("data-y")) || 0) + event.dy;
    target.style.transform = `translate(${x}px, ${y}px)`;
    target.setAttribute("data-x", x);
    target.setAttribute("data-y", y);
  },
  dragEndListener(event) {
    event.target.classList.remove("dragging");
  },
  resetPositions() {
    const elementsToReset = [
      "#card-logo",
      "#card-personal-photo-wrapper",
      "#card-name",
      "#card-tagline",
      "#qr-code-wrapper",
      ".phone-button-draggable-wrapper",
      ".draggable-social-link",
    ];
    elementsToReset.forEach((selector) => {
      document.querySelectorAll(selector).forEach((el) => {
        if (el) {
          el.style.transform = "translate(0px, 0px)";
          el.removeAttribute("data-x");
          el.removeAttribute("data-y");
        }
      });
    });
  },
};

const CardManager = {
  frontBgImageUrl: null,
  backBgImageUrl: null,
  qrCodeImageUrl: null,
  personalPhotoUrl: null,
  autoGeneratedQrDataUrl: null,
  updateElementFromInput(input) {
    const { updateTarget, updateProperty, updateUnit = "" } = input.dataset;
    if (!updateTarget || !updateProperty) return;
    const targetElement = document.getElementById(updateTarget);
    if (!targetElement) return;
    const properties = updateProperty.split(".");
    let current = targetElement;
    for (let i = 0; i < properties.length - 1; i++) {
      current = current[properties[i]];
    }
    current[properties[properties.length - 1]] = input.value + updateUnit;
  },

  updatePersonalPhotoStyles() {
    const wrapper = DOMElements.draggable.photo;
    if (!wrapper) return;

    const imageUrl = DOMElements.photoControls.url.value;
    const size = DOMElements.photoControls.size.value;
    const shape = document.querySelector(
      'input[name="photo-shape"]:checked',
    ).value;
    const borderColor = DOMElements.photoControls.borderColor.value;
    const borderWidth = DOMElements.photoControls.borderWidth.value;

    // استخدام دالة التحقق الآمنة من security-utils.js إذا كانت متوفرة
    const safeUrl =
      typeof sanitizeURL === "function" ? sanitizeURL(imageUrl) : imageUrl;

    wrapper.style.width = `${size}%`;
    wrapper.style.height = `${size}%`;
    wrapper.style.borderRadius = shape === "circle" ? "50%" : "8px";
    wrapper.style.border = `${borderWidth}px solid ${borderColor}`;
    wrapper.style.backgroundImage = safeUrl ? `url(${safeUrl})` : "none";
    wrapper.style.display = safeUrl ? "block" : "none";
  },

  updatePhoneButtonStyles() {
    const bgColor = DOMElements.phoneBtnBgColor.value;
    const textColor = DOMElements.phoneBtnTextColor.value;
    const fontSize = DOMElements.phoneBtnFontSize.value;
    const fontFamily = DOMElements.phoneBtnFont.value;
    const padding = DOMElements.phoneBtnPadding.value;
    document.querySelectorAll(".phone-button").forEach((button) => {
      button.style.backgroundColor = bgColor;
      button.style.color = textColor;
      button.style.borderColor =
        bgColor === "transparent" || bgColor.includes("rgba(0,0,0,0)")
          ? textColor
          : "transparent";
      button.style.fontSize = `${fontSize}px`;
      button.style.fontFamily = fontFamily;
      button.style.padding = `${padding}px ${padding * 2}px`;
    });
  },
  updatePhoneButtonsVisibility() {
    const isVisible = DOMElements.buttons.togglePhone.checked;
    document
      .querySelectorAll(".phone-button-draggable-wrapper")
      .forEach((wrapper) => {
        wrapper.classList.toggle("text-only-mode", !isVisible);
      });
    DOMElements.phoneTextControls.container.classList.toggle(
      "visible",
      !isVisible,
    );
  },

  updatePhoneTextStyles() {
    const layout = document.querySelector(
      'input[name="phone-text-layout"]:checked',
    ).value;
    const size = DOMElements.phoneTextControls.size.value;
    const color = DOMElements.phoneTextControls.color.value;
    const font = DOMElements.phoneTextControls.font.value;
    document
      .querySelectorAll(".phone-button-draggable-wrapper")
      .forEach((wrapper) => {
        wrapper.dataset.layout = layout;
        const button = wrapper.querySelector(".phone-button");
        if (button) {
          button.style.fontSize = `${size}px`;
          button.style.color = color;
          button.style.fontFamily = font;
        }
      });
  },

  // --- (Safe Refactor) دالة عرض أزرار الهاتف الآمنة ---
  renderPhoneButtons() {
    document
      .querySelectorAll(".phone-button-draggable-wrapper")
      .forEach((el) => el.remove());

    const state = StateManager.getStateObject();
    const phoneState = state.dynamic.phones || [];

    DOMElements.phoneNumbersContainer
      .querySelectorAll(".dynamic-input-group")
      .forEach((group) => {
        const phoneId = group.dataset.phoneId;
        const phoneData = phoneState.find((p) => p.id === phoneId);
        if (!phoneData || !phoneData.value) return;

        const placement = phoneData.placement || "front";
        const parentContainer =
          placement === "front"
            ? DOMElements.cardFrontContent
            : DOMElements.cardBackContent;

        const pos = phoneData.position || { x: 0, y: 0 };

        // استخدام createElement لإنشاء العناصر بأمان
        const wrapper = createElement("div", {
          id: phoneId,
          className: "phone-button-draggable-wrapper draggable-on-card",
          "data-control-id": group.id,
          style: {
            position: "absolute",
            transform: `translate(${pos.x}px, ${pos.y}px)`,
          },
          "data-x": pos.x,
          "data-y": pos.y,
        });

        const phoneLink = createElement("a", {
          href: `tel:${phoneData.value.replace(/[^0-9+]/g, "")}`,
          className: "phone-button",
        });

        const icon = createElement("i", {
          className: "fas fa-phone-alt",
          "aria-hidden": "true",
        });
        const span = createElement("span", { textContent: phoneData.value });

        const copyBtn = createElement("button", {
          className: "copy-btn no-export",
          title: "نسخ الرقم",
          "aria-label": `نسخ الرقم ${phoneData.value}`,
          onclick: (e) => {
            e.preventDefault();
            e.stopPropagation();
            // استخدام دالة النسخ الآمنة
            if (typeof Utils.copyTextToClipboard === "function") {
              Utils.copyTextToClipboard(phoneData.value).then((success) => {
                if (success) UIManager.announce("تم نسخ الرقم!");
              });
            }
          },
        });

        const copyIcon = createElement("i", {
          className: "fas fa-copy",
          "aria-hidden": "true",
        });
        copyBtn.appendChild(copyIcon);

        phoneLink.appendChild(icon);
        phoneLink.appendChild(span);
        phoneLink.appendChild(copyBtn);

        phoneLink.addEventListener("click", (e) => {
          e.preventDefault();
          UIManager.navigateToAndHighlight(wrapper.dataset.controlId);
        });

        wrapper.appendChild(phoneLink);

        const hint = createElement("i", {
          className: "fas fa-arrows-alt dnd-hover-hint",
        });
        wrapper.appendChild(hint);

        parentContainer.appendChild(wrapper);
        DragManager.makeDraggable(`#${phoneId}`);
      });

    this.updatePhoneButtonStyles();
    this.updatePhoneButtonsVisibility();
    this.updatePhoneTextStyles();
  },

  createPhoneInput(phoneData = {}) {
    const {
      id = `phone_${Date.now()}`,
      value = "",
      placement = "front",
    } = phoneData;

    const inputGroup = document.createElement("div");
    inputGroup.className = "dynamic-input-group";
    inputGroup.id = `phone-control-${id}`;
    inputGroup.dataset.phoneId = id;

    const mainContent = document.createElement("div");
    mainContent.style.flexGrow = "1";

    const inputWrapper = document.createElement("div");
    inputWrapper.style.display = "flex";
    inputWrapper.style.alignItems = "center";
    inputWrapper.style.gap = "10px";

    const dragHandle = document.createElement("i");
    dragHandle.className = "fas fa-grip-vertical drag-handle";
    dragHandle.setAttribute("aria-hidden", "true");

    const newPhoneInput = document.createElement("input");
    newPhoneInput.type = "tel";
    newPhoneInput.value = value;
    newPhoneInput.placeholder = "رقم هاتف جديد";
    newPhoneInput.style.flexGrow = "1";

    const removeBtn = document.createElement("button");
    removeBtn.className = "remove-btn";
    removeBtn.textContent = "×";
    removeBtn.setAttribute("aria-label", "حذف رقم الهاتف");

    inputWrapper.append(dragHandle, newPhoneInput, removeBtn);

    const placementControl = document.createElement("div");
    placementControl.className = "placement-control";
    placementControl.innerHTML = `
            <div class="radio-group">
                <label><input type="radio" name="placement-${id}" value="front" ${placement === "front" ? "checked" : ""}> أمامي</label>
                <label><input type="radio" name="placement-${id}" value="back" ${placement === "back" ? "checked" : ""}> خلفي</label>
            </div>
        `;

    const positionControl = document.createElement("div");
    positionControl.className = "form-group";
    positionControl.innerHTML = `
            <label>تحريك دقيق (بالبكسل)</label>
            <div class="position-controls-grid" data-target-id="${id}"> 
                <button type="button" class="btn-icon move-btn" data-direction="up" title="للأعلى"><i class="fas fa-arrow-up"></i></button>
                <div class="controls-row">
                    <button type="button" class="btn-icon move-btn" data-direction="left" title="لليسار"><i class="fas fa-arrow-left"></i></button>
                    <button type="button" class="btn-icon move-btn" data-direction="right" title="لليمين"><i class="fas fa-arrow-right"></i></button>
                </div>
                <button type="button" class="btn-icon move-btn" data-direction="down" title="للأسفل"><i class="fas fa-arrow-down"></i></button>
            </div>
        `;

    mainContent.append(inputWrapper, placementControl, positionControl);
    inputGroup.appendChild(mainContent);

    const handleUpdate = () => {
      this.renderPhoneButtons();
    };
    removeBtn.onclick = () => {
      inputGroup.remove();
      handleUpdate();
    };
    newPhoneInput.addEventListener("input", () => {
      handleUpdate();
      CardManager.generateVCardQrDebounced();
    });
    placementControl
      .querySelectorAll('input[type="radio"]')
      .forEach((radio) => radio.addEventListener("change", handleUpdate));

    positionControl.querySelectorAll(".move-btn").forEach((button) => {
      button.addEventListener("click", (e) => {
        e.preventDefault();
        EventManager.moveElement(id, button.dataset.direction);
      });
    });

    DOMElements.phoneNumbersContainer.appendChild(inputGroup);
  },

  updateCardBackgrounds() {
    const setBg = (
      imageLayer,
      gradientLayer,
      startId,
      endId,
      image,
      opacityId,
    ) => {
      if (!imageLayer || !gradientLayer) return;
      const startColor = document.getElementById(startId).value;
      const endColor = document.getElementById(endId).value;

      let opacity = document.getElementById(opacityId).value;
      const opacityControl = document
        .getElementById(opacityId)
        .closest(".form-group");

      if (!image) {
        opacity = 1;
        if (opacityControl) opacityControl.style.display = "none";
      } else {
        if (opacityControl) opacityControl.style.display = "block";
      }

      // Sanitize Background URL
      const safeBg =
        typeof sanitizeURL === "function" && image ? sanitizeURL(image) : image;
      imageLayer.style.backgroundImage = safeBg ? `url(${safeBg})` : "none";

      gradientLayer.style.backgroundImage = `linear-gradient(135deg, ${startColor}, ${endColor})`;
      gradientLayer.style.opacity = opacity;
    };

    setBg(
      document.getElementById("front-bg-image-layer"),
      document.getElementById("front-bg-gradient-layer"),
      "front-bg-start",
      "front-bg-end",
      this.frontBgImageUrl,
      "front-bg-opacity",
    );
    setBg(
      document.getElementById("back-bg-image-layer"),
      document.getElementById("back-bg-gradient-layer"),
      "back-bg-start",
      "back-bg-end",
      this.backBgImageUrl,
      "back-bg-opacity",
    );
  },

  renderCardContent() {
    const state = StateManager.getStateObject();
    if (!state || !state.placements) return;

    const containers = {
      front: DOMElements.cardFrontContent,
      back: DOMElements.cardBackContent,
    };
    const elements = {
      logo: DOMElements.draggable.logo,
      photo: DOMElements.draggable.photo,
      name: DOMElements.draggable.name,
      tagline: DOMElements.draggable.tagline,
      qr: DOMElements.draggable.qr,
    };

    Object.values(elements).forEach((el) => el.parentNode?.removeChild(el));

    for (const [key, side] of Object.entries(state.placements)) {
      if (elements[key] && containers[side]) {
        elements[key].style.position = "absolute";
        containers[side].appendChild(elements[key]);
      }
    }

    this.updatePersonalPhotoStyles();
    this.renderPhoneButtons();
    this.updateSocialLinks();
  },

  // --- (Safe Refactor) عرض QR Code الآمن ---
  updateQrCodeDisplay() {
    const qrSourceRadio = document.querySelector(
      'input[name="qr-source"]:checked',
    );
    if (!qrSourceRadio) return;

    const qrSource = qrSourceRadio.value;
    const qrWrapper = DOMElements.draggable.qr;
    qrWrapper.innerHTML = ""; // Clear existing

    let qrImage = "";

    if (qrSource === "custom") {
      qrImage = DOMElements.qrImageUrlInput.value;
    } else if (qrSource === "upload") {
      qrImage = this.qrCodeImageUrl;
    } else if (qrSource === "auto-card" || qrSource === "auto-vcard") {
      qrImage = this.autoGeneratedQrDataUrl;
    }

    if (qrImage) {
      // استخدام sanitizeURL و createElement
      const safeUrl =
        typeof sanitizeURL === "function" ? sanitizeURL(qrImage) : qrImage;

      if (safeUrl) {
        const img = createElement("img", {
          src: safeUrl,
          alt: "QR Code",
          style: {
            width: "100%",
            height: "100%",
            borderRadius: "4px",
            objectFit: "contain",
          },
        });
        qrWrapper.appendChild(img);
      }
    }

    const hint = createElement("i", {
      className: "fas fa-arrows-alt dnd-hover-hint",
    });
    qrWrapper.appendChild(hint);

    qrWrapper.style.width = `${DOMElements.qrSizeSlider.value}%`;
  },

  handleMasterSocialToggle() {
    const isEnabled = DOMElements.buttons.toggleMasterSocial
      ? DOMElements.buttons.toggleMasterSocial.checked
      : true;
    if (DOMElements.socialControlsWrapper) {
      DOMElements.socialControlsWrapper.style.display = isEnabled
        ? "block"
        : "none";
    }
    this.updateSocialLinks();
  },

  updateSocialLinksVisibility() {
    const isVisibleAsButtons = DOMElements.buttons.toggleSocial.checked;
    DOMElements.socialTextControls.container.classList.toggle(
      "visible",
      !isVisibleAsButtons,
    );
    document.querySelectorAll(".draggable-social-link").forEach((wrapper) => {
      wrapper.classList.toggle("text-only-mode", !isVisibleAsButtons);
    });
  },

  updateSocialButtonStyles() {
    const backButtonBgColor = DOMElements.backButtonsBgColor.value;
    const backButtonTextColor = DOMElements.backButtonsTextColor.value;
    const backButtonFont = DOMElements.backButtonsFont.value;
    const backButtonSize = DOMElements.backButtonsSize.value;

    document
      .querySelectorAll(".draggable-social-link:not(.text-only-mode) a")
      .forEach((link) => {
        Object.assign(link.style, {
          backgroundColor: backButtonBgColor,
          color: backButtonTextColor,
          fontFamily: backButtonFont,
          fontSize: `${backButtonSize}px`,
          padding: `${backButtonSize * 0.5}px ${backButtonSize}px`,
        });
        const icon = link.querySelector("i");
        const span = link.querySelector("span");
        if (icon) icon.style.color = "";
        if (span) {
          span.style.color = "";
          span.style.fontSize = "";
          span.style.fontFamily = "";
        }
      });
  },

  updateSocialTextStyles() {
    const generalSize = DOMElements.socialTextControls.size.value;
    const generalColor = DOMElements.socialTextControls.color.value;
    const generalFont = DOMElements.socialTextControls.font.value;

    document
      .querySelectorAll(".draggable-social-link.text-only-mode")
      .forEach((wrapper) => {
        const link = wrapper.querySelector("a");
        if (!link) return;

        const icon = link.querySelector("i");
        const span = link.querySelector("span");
        const controlId = wrapper.dataset.controlId;

        let specificColor = null;
        let specificSize = null;

        if (controlId && controlId.startsWith("form-group-static-")) {
          const type = controlId.replace("form-group-static-", "");
          specificColor = document.getElementById(
            `input-static-${type}-color`,
          )?.value;
          specificSize = document.getElementById(
            `input-static-${type}-size`,
          )?.value;
        } else if (
          controlId &&
          controlId.startsWith("social-control-dynsocial_")
        ) {
          const id = controlId.replace("social-control-", "");
          specificColor = document.getElementById(`input-${id}-color`)?.value;
          specificSize = document.getElementById(`input-${id}-size`)?.value;
        }

        const finalColor =
          specificColor && specificColor !== "#e6f0f7"
            ? specificColor
            : generalColor;
        const finalSize =
          specificSize && specificSize !== "12" ? specificSize : generalSize;

        Object.assign(link.style, {
          color: finalColor,
          backgroundColor: "transparent",
          padding: "2px",
          fontSize: "",
          fontFamily: "",
        });
        if (icon) icon.style.color = finalColor;
        if (span) {
          span.style.fontSize = `${finalSize}px`;
          span.style.color = finalColor;
          span.style.fontFamily = generalFont;
        }
      });
  },

  // --- (Safe Refactor) عرض روابط التواصل الآمنة ---
  updateSocialLinks() {
    document
      .querySelectorAll(".draggable-social-link")
      .forEach((el) => el.remove());

    const isMasterEnabled = DOMElements.buttons.toggleMasterSocial
      ? DOMElements.buttons.toggleMasterSocial.checked
      : true;
    if (!isMasterEnabled) return;

    const state = StateManager.getStateObject();
    if (!state) return;

    const renderLink = (linkData) => {
      const { id, value, placement, platform, controlId, position } = linkData;
      if (!value) return;

      const parentContainer =
        placement === "front"
          ? DOMElements.cardFrontContent
          : DOMElements.cardBackContent;
      const elementId = id.startsWith("static-")
        ? `social-link-${id}`
        : `social-link-${id.replace(/[^a-zA-Z0-9-]/g, "-")}`;

      const pos = position || { x: 0, y: 0 };

      // إنشاء Wrapper بأمان
      const linkWrapper = createElement("div", {
        id: elementId,
        className: "draggable-social-link draggable-on-card",
        "data-control-id": controlId,
        style: {
          position: "absolute",
          transform: `translate(${pos.x}px, ${pos.y}px)`,
        },
        "data-x": pos.x,
        "data-y": pos.y,
      });

      let fullUrl = value,
        displayText = value;
      if (platform.prefix) {
        if (platform.id === "email" || platform.id === "whatsapp") {
          fullUrl = platform.prefix + value;
        } else {
          fullUrl = !/^(https?:\/\/)/i.test(value)
            ? platform.prefix + value
            : value;
        }
      } else if (!/^(https?:\/\/)/i.test(value)) {
        fullUrl = "https://" + value;
      }
      if (platform.id !== "email" && platform.id !== "whatsapp") {
        displayText = displayText
          .replace(/^(https?:\/\/)?(www\.)?/, "")
          .replace(/\/$/, "");
      }

      const safeUrl =
        typeof sanitizeURL === "function" ? sanitizeURL(fullUrl) : fullUrl;

      const linkElement = createElement("a", {
        href: safeUrl || "#",
        target: "_blank",
        rel: "noopener noreferrer",
      });

      const icon = createElement("i", {
        className: platform.icon,
        "aria-hidden": "true",
      });
      const textSpan = createElement("span", { textContent: displayText });

      const copyBtn = createElement("button", {
        className: "copy-btn no-export",
        title: "نسخ الرابط",
        "aria-label": `نسخ الرابط ${displayText}`,
        onclick: (e) => {
          e.preventDefault();
          e.stopPropagation();
          if (typeof Utils.copyTextToClipboard === "function") {
            Utils.copyTextToClipboard(fullUrl).then((success) => {
              if (success) UIManager.announce("تم نسخ الرابط!");
            });
          }
        },
      });

      const copyIcon = createElement("i", {
        className: "fas fa-copy",
        "aria-hidden": "true",
      });
      copyBtn.appendChild(copyIcon);

      linkElement.appendChild(icon);
      linkElement.appendChild(textSpan);
      linkElement.appendChild(copyBtn);

      linkWrapper.appendChild(linkElement);

      const hint = createElement("i", {
        className: "fas fa-arrows-alt dnd-hover-hint",
      });
      linkWrapper.appendChild(hint);

      linkElement.addEventListener("click", (e) => {
        if (!e.metaKey && !e.ctrlKey) {
          e.preventDefault();
          UIManager.navigateToAndHighlight(controlId);
        }
      });

      parentContainer.appendChild(linkWrapper);
      DragManager.makeDraggable(`#${elementId}`);
    };

    if (state.dynamic.staticSocial) {
      Config.STATIC_CONTACT_METHODS.forEach((method) => {
        const socialState = state.dynamic.staticSocial[method.id];
        if (socialState && socialState.value) {
          renderLink({
            id: `static-${method.id}`,
            value: socialState.value,
            placement: socialState.placement,
            position: socialState.position,
            platform: method,
            controlId: `form-group-static-${method.id}`,
          });
        }
      });
    }

    if (state.dynamic.social) {
      state.dynamic.social.forEach((link, index) => {
        if (
          link.platform &&
          link.value &&
          Config.SOCIAL_PLATFORMS[link.platform]
        ) {
          renderLink({
            id: link.id || `dynamic-${link.platform}-${index}`,
            value: link.value,
            placement: link.placement,
            position: link.position,
            platform: Config.SOCIAL_PLATFORMS[link.platform],
            controlId: link.id
              ? `social-control-${link.id}`
              : `social-media-input`,
          });
        }
      });
    }

    this.updateSocialLinksVisibility();
    this.updateSocialButtonStyles();
    this.updateSocialTextStyles();
  },

  async generateVCardQr() {
    const qrSource = document.querySelector(
      'input[name="qr-source"]:checked',
    )?.value;
    if (qrSource !== "auto-vcard") return;

    const vCardData = ExportManager.getVCardString();
    if (vCardData.length < 30) {
      this.autoGeneratedQrDataUrl = null;
      this.updateQrCodeDisplay();
      return;
    }

    try {
      await Utils.loadScript(Config.SCRIPT_URLS.qrCodeStyling);

      const currentLogo = DOMElements.draggable.logo.src;
      const isDefaultLogo = currentLogo.includes(
        "mcprime-logo-transparent.png",
      );

      // Sanitize logo URL
      const safeLogo =
        typeof sanitizeURL === "function"
          ? sanitizeURL(currentLogo)
          : currentLogo;

      const qrCode = new QRCodeStyling({
        width: 300,
        height: 300,
        data: vCardData,
        image: isDefaultLogo ? null : safeLogo,
        dotsOptions: {
          color: "#000000",
          type: "rounded",
        },
        backgroundOptions: {
          color: "#ffffff",
        },
        imageOptions: {
          crossOrigin: "anonymous",
          margin: 10,
          imageSize: 0.4,
        },
        cornersSquareOptions: {
          type: "extra-rounded",
        },
      });

      const container = DOMElements.qrCodeTempGenerator;
      container.innerHTML = "";

      await qrCode.append(container);

      setTimeout(() => {
        const canvas = container.querySelector("canvas");
        if (canvas) {
          this.autoGeneratedQrDataUrl = canvas.toDataURL();
          this.updateQrCodeDisplay();
        }
        container.innerHTML = "";
      }, 100);
    } catch (error) {
      console.error("Failed to generate Styled QR code:", error);
    }
  },

  async generateCardLinkQr() {
    const button = DOMElements.buttons.generateAutoQr;
    UIManager.setButtonLoadingState(button, true, "جاري الحفظ...");
    try {
      await Utils.loadScript(Config.SCRIPT_URLS.qrCodeStyling);
      const designId = await ShareManager.saveDesign();
      if (!designId) {
        alert("فشل حفظ التصميم اللازم لإنشاء الرابط.");
        return;
      }

      UIManager.setButtonLoadingState(button, true, "جاري الإنشاء...");
      const viewerUrl = new URL("viewer.html", window.location.href);
      viewerUrl.searchParams.set("id", designId);
      const finalUrl = viewerUrl.href;

      const currentLogo = DOMElements.draggable.logo.src;
      const isDefaultLogo = currentLogo.includes(
        "mcprime-logo-transparent.png",
      );
      const safeLogo =
        typeof sanitizeURL === "function"
          ? sanitizeURL(currentLogo)
          : currentLogo;

      const qrCode = new QRCodeStyling({
        width: 300,
        height: 300,
        data: finalUrl,
        image: isDefaultLogo ? null : safeLogo,
        dotsOptions: {
          color: "#000000",
          type: "rounded",
        },
        backgroundOptions: {
          color: "#ffffff",
        },
        imageOptions: {
          crossOrigin: "anonymous",
          margin: 10,
          imageSize: 0.4,
        },
        cornersSquareOptions: {
          type: "extra-rounded",
        },
      });

      const container = DOMElements.qrCodeTempGenerator;
      container.innerHTML = "";
      await qrCode.append(container);

      setTimeout(() => {
        const canvas = container.querySelector("canvas");
        if (canvas) {
          this.autoGeneratedQrDataUrl = canvas.toDataURL();
          this.updateQrCodeDisplay();
          UIManager.announce("تم إنشاء QR Code بنجاح.");
        } else {
          alert("حدث خطأ أثناء إنشاء QR Code.");
        }
        container.innerHTML = "";
      }, 100);
    } catch (error) {
      console.error("Error generating shareable QR code:", error);
      alert("حدث خطأ. لم نتمكن من إنشاء رابط QR Code.");
    } finally {
      UIManager.setButtonLoadingState(button, false);
    }
  },

  generateVCardQrDebounced: Utils.debounce(() => {
    CardManager.generateVCardQr();
  }, 400),

  applyTheme(themeKey) {
    const theme = Config.THEMES[themeKey];
    if (!theme) return;

    UIManager.setActiveThumbnail(themeKey);

    const controlsToUpdate = {
      "name-color": theme.values.textPrimary,
      "tagline-color": theme.values.taglineColor,
      "front-bg-start": theme.gradient[0],
      "front-bg-end": theme.gradient[1],
      "back-bg-start": theme.gradient[0],
      "back-bg-end": theme.gradient[1],
      "back-buttons-bg-color": theme.values.backButtonBg,
      "back-buttons-text-color": theme.values.backButtonText,
      "phone-btn-bg-color": theme.values.phoneBtnBg,
      "phone-btn-text-color": theme.values.phoneBtnText,
    };
    for (const [id, value] of Object.entries(controlsToUpdate)) {
      const control = document.getElementById(id);
      if (control) {
        control.value = value;
        control.dispatchEvent(new Event("input", { bubbles: true }));
      }
    }

    this.frontBgImageUrl = null;
    this.backBgImageUrl = null;
    DOMElements.fileInputs.frontBg.value = "";
    DOMElements.fileInputs.backBg.value = "";

    this.updateCardBackgrounds();
    UIManager.announce(`تم تطبيق تصميم ${theme.name}`);
  },
  addSocialLink() {
    const platformKey = DOMElements.social.typeSelect.value;
    const value = DOMElements.social.input.value.trim();
    if (!value) {
      UIManager.announce("الرجاء إدخال رابط أو معرف.");
      return;
    }

    const platform = Config.SOCIAL_PLATFORMS[platformKey];
    const id = `dynsocial_${Date.now()}`;

    const linkEl = document.createElement("div");
    linkEl.className = "dynamic-input-group dynamic-social-link";
    linkEl.id = `social-control-${id}`;
    linkEl.dataset.socialId = id;
    linkEl.dataset.platform = platformKey;
    linkEl.dataset.value = value;

    const mainContent = document.createElement("div");
    mainContent.style.flexGrow = "1";

    const infoWrapper = document.createElement("div");
    infoWrapper.style.display = "flex";
    infoWrapper.style.alignItems = "center";
    infoWrapper.style.gap = "10px";

    // استخدام createElement للأمان (يمكن استبدال innerHTML هنا)
    // لكن بما أن هذا الجزء في المحرر (Editor UI) وليس في المعاينة،
    // فالخطورة أقل، لكن للأفضل:
    infoWrapper.innerHTML = `
            <i class="fas fa-grip-vertical drag-handle"></i>
            <i class="${platform.icon}" aria-hidden="true"></i>
            <span style="flex-grow: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">${platform.name}: ${value.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</span>
            <button class="remove-btn" aria-label="حذف رابط ${platform.name}">×</button>
        `;

    const elementId = `social-link-${id.replace(/[^a-zA-Z0-9-]/g, "-")}`;

    const placementControl = document.createElement("div");
    placementControl.className = "placement-control";
    placementControl.innerHTML = `
            <div class="radio-group">
                <label><input type="radio" name="placement-${id}" value="front"> أمامي</label>
                <label><input type="radio" name="placement-${id}" value="back" checked> خلفي</label>
            </div>
        `;

    const positionControl = document.createElement("div");
    positionControl.className = "form-group";
    positionControl.innerHTML = `
            <label>تحريك دقيق (بالبكسل)</label>
            <div class="position-controls-grid" data-target-id="${elementId}"> 
                <button type="button" class="btn-icon move-btn" data-direction="up" title="للأعلى"><i class="fas fa-arrow-up"></i></button>
                <div class="controls-row">
                    <button type="button" class="btn-icon move-btn" data-direction="left" title="لليسار"><i class="fas fa-arrow-left"></i></button>
                    <button type="button" class="btn-icon move-btn" data-direction="right" title="لليمين"><i class="fas fa-arrow-right"></i></button>
                </div>
                <button type="button" class="btn-icon move-btn" data-direction="down" title="للأسفل"><i class="fas fa-arrow-down"></i></button>
            </div>
        `;

    const formattingControl = document.createElement("details");
    formattingControl.className = "fieldset-accordion";
    formattingControl.style.backgroundColor = "var(--page-bg)";
    formattingControl.innerHTML = `
            <summary style="padding: 8px 12px; font-size: 0.9rem;">تنسيقات خاصة (للنص)</summary>
            <div class="fieldset-content" style="padding: 10px;">
                <div class="control-grid">
                    <div class="form-group">
                        <label for="input-${id}-color">لون الخط</label>
                        <input type="color" id="input-${id}-color" value="#e6f0f7">
                    </div>
                    <div class="form-group">
                        <label for="input-${id}-size">حجم الخط</label>
                        <input type="range" id="input-${id}-size" min="10" max="24" value="12">
                    </div>
                </div>
            </div>
        `;

    mainContent.append(
      infoWrapper,
      placementControl,
      positionControl,
      formattingControl,
    );
    linkEl.appendChild(mainContent);

    const handleUpdate = () => {
      this.updateSocialLinks();
      this.generateVCardQrDebounced();
    };
    infoWrapper.querySelector(".remove-btn").addEventListener("click", () => {
      linkEl.remove();
      handleUpdate();
    });
    placementControl
      .querySelectorAll('input[type="radio"]')
      .forEach((radio) => radio.addEventListener("change", handleUpdate));

    positionControl.querySelectorAll(".move-btn").forEach((button) => {
      button.addEventListener("click", (e) => {
        e.preventDefault();
        EventManager.moveElement(elementId, button.dataset.direction);
      });
    });

    formattingControl.querySelectorAll("input").forEach((input) => {
      input.addEventListener("input", () => {
        this.updateSocialTextStyles();
      });
    });

    DOMElements.social.container.appendChild(linkEl);
    DOMElements.social.input.value = "";
    handleUpdate();
  },
  applyLayout(layoutName = "classic") {
    DOMElements.cardsWrapper.dataset.layout = layoutName;
  },
  applyBackground(bgUrl) {
    const targetSide =
      document.querySelector('input[name="bg-gallery-target"]:checked')
        ?.value || "front";
    const safeUrl =
      typeof sanitizeURL === "function" ? sanitizeURL(bgUrl) : bgUrl;

    if (targetSide === "front") {
      this.frontBgImageUrl = safeUrl;
      document.getElementById("front-bg-start").value = "#000000";
      document.getElementById("front-bg-end").value = "#000000";
      document.getElementById("front-bg-opacity").value = 0.3;
      DOMElements.buttons.removeFrontBg.style.display = "block";
    } else {
      this.backBgImageUrl = safeUrl;
      document.getElementById("back-bg-start").value = "#000000";
      document.getElementById("back-bg-end").value = "#000000";
      document.getElementById("back-bg-opacity").value = 0.3;
      DOMElements.buttons.removeBackBg.style.display = "block";
    }

    this.updateCardBackgrounds();
    UIManager.announce(
      `تم تطبيق خلفية ${targetSide === "front" ? "أمامية" : "خلفية"} جديدة.`,
    );
  },
};

const StateManager = {
  isApplyingState: false,

  getStateObject() {
    const state = {
      inputs: {},
      dynamic: { phones: [], social: [], staticSocial: {} },
      imageUrls: {},
      positions: {},
      placements: {},
    };

    document.querySelectorAll("input, select, textarea").forEach((input) => {
      if (input.type === "radio" && !input.name.startsWith("placement-")) {
        if (input.checked) {
          state.inputs[input.name] = input.value;
        }
      } else if (input.type === "checkbox") {
        state.inputs[input.id] = input.checked;
      } else if (!input.name.startsWith("placement-")) {
        state.inputs[input.id] = input.value;
      }
    });

    DOMElements.phoneNumbersContainer
      .querySelectorAll(".dynamic-input-group")
      .forEach((group) => {
        const phoneId = group.dataset.phoneId;
        const phoneInput = group.querySelector('input[type="tel"]');
        const placementInput = group.querySelector(
          `input[name="placement-${phoneId}"]:checked`,
        );
        const cardElement = document.getElementById(phoneId);

        if (phoneId && phoneInput) {
          state.dynamic.phones.push({
            id: phoneId,
            value: phoneInput.value,
            placement: placementInput ? placementInput.value : "front",
            position: cardElement
              ? {
                  x: parseFloat(cardElement.getAttribute("data-x")) || 0,
                  y: parseFloat(cardElement.getAttribute("data-y")) || 0,
                }
              : { x: 0, y: 0 },
          });
        }
      });

    DOMElements.social.container
      .querySelectorAll(".dynamic-social-link")
      .forEach((group) => {
        const socialId = group.dataset.socialId;
        const placementInput = group.querySelector(
          `input[name="placement-${socialId}"]:checked`,
        );
        const cardElement = document.getElementById(
          `social-link-${socialId.replace(/[^a-zA-Z0-9-]/g, "-")}`,
        );

        const colorInput = group.querySelector(`#input-${socialId}-color`);
        const sizeInput = group.querySelector(`#input-${socialId}-size`);

        if (socialId) {
          state.dynamic.social.push({
            id: socialId,
            platform: group.dataset.platform,
            value: group.dataset.value,
            placement: placementInput ? placementInput.value : "back",
            position: cardElement
              ? {
                  x: parseFloat(cardElement.getAttribute("data-x")) || 0,
                  y: parseFloat(cardElement.getAttribute("data-y")) || 0,
                }
              : { x: 0, y: 0 },
            color: colorInput ? colorInput.value : "#e6f0f7",
            size: sizeInput ? sizeInput.value : 12,
          });
        }
      });

    Config.STATIC_CONTACT_METHODS.forEach((method) => {
      const controlGroup = document.getElementById(
        `form-group-static-${method.id}`,
      );
      const input = document.getElementById(`input-${method.id}`);
      const placementInput = controlGroup
        ? controlGroup.querySelector(
            `input[name="placement-static-${method.id}"]:checked`,
          )
        : null;
      const cardElement = document.getElementById(
        `social-link-static-${method.id}`,
      );

      if (input) {
        state.dynamic.staticSocial[method.id] = {
          value: input.value,
          placement: placementInput ? placementInput.value : "back",
          position: cardElement
            ? {
                x: parseFloat(cardElement.getAttribute("data-x")) || 0,
                y: parseFloat(cardElement.getAttribute("data-y")) || 0,
              }
            : { x: 0, y: 0 },
        };
      }
    });

    state.imageUrls.front = CardManager.frontBgImageUrl;
    state.imageUrls.back = CardManager.backBgImageUrl;
    state.imageUrls.qrCode = CardManager.qrCodeImageUrl;
    state.imageUrls.photo = CardManager.personalPhotoUrl;

    const coreElements = [
      "card-logo",
      "card-personal-photo-wrapper",
      "card-name",
      "card-tagline",
      "qr-code-wrapper",
    ];
    coreElements.forEach((id) => {
      const el = document.getElementById(id);
      if (el) {
        state.positions[id] = {
          x: parseFloat(el.getAttribute("data-x")) || 0,
          y: parseFloat(el.getAttribute("data-y")) || 0,
        };
      }
    });

    const placementElements = ["logo", "photo", "name", "tagline", "qr"];
    placementElements.forEach((elName) => {
      const checkedRadio = document.querySelector(
        `input[name="placement-${elName}"]:checked`,
      );
      if (checkedRadio) {
        state.placements[elName] = checkedRadio.value;
      }
    });

    return state;
  },

  save() {
    try {
      const state = this.getStateObject();
      localStorage.setItem(Config.LOCAL_STORAGE_KEY, JSON.stringify(state));
    } catch (e) {
      console.error("Failed to save state:", e);
    }
  },
  load() {
    try {
      const savedState = localStorage.getItem(Config.LOCAL_STORAGE_KEY);
      if (savedState) {
        this.applyState(JSON.parse(savedState), false);
        return true;
      }
      return false;
    } catch (e) {
      console.error("Failed to load state:", e);
      return false;
    }
  },

  applyState(state, triggerSave = true) {
    if (!state) return;

    this.isApplyingState = true;

    if (state.inputs) {
      for (const [key, value] of Object.entries(state.inputs)) {
        const radioInputs = document.querySelectorAll(
          `input[name="${key}"][type="radio"]`,
        );
        if (radioInputs.length > 0) {
          radioInputs.forEach(
            (radio) => (radio.checked = radio.value === value),
          );
        } else {
          const input = document.getElementById(key);
          if (input) {
            if (input.type === "checkbox") {
              input.checked = value;
            } else {
              input.value = value || "";
            }
          }
        }
      }
    }

    DOMElements.phoneNumbersContainer.innerHTML = "";
    if (state.dynamic && state.dynamic.phones) {
      state.dynamic.phones.forEach((phoneData) =>
        CardManager.createPhoneInput(phoneData),
      );
    }

    DOMElements.social.container.innerHTML = "";
    if (state.dynamic && state.dynamic.social) {
      state.dynamic.social.forEach((socialData) => {
        DOMElements.social.typeSelect.value = socialData.platform;
        DOMElements.social.input.value = socialData.value;
        CardManager.addSocialLink();

        const newControl = document.getElementById(
          `social-control-${socialData.id}`,
        );
        if (newControl) {
          const placementRadio = newControl.querySelector(
            `input[value="${socialData.placement}"]`,
          );
          if (placementRadio) placementRadio.checked = true;

          const colorInput = newControl.querySelector(
            `#input-${socialData.id}-color`,
          );
          const sizeInput = newControl.querySelector(
            `#input-${socialData.id}-size`,
          );
          if (colorInput && socialData.color)
            colorInput.value = socialData.color;
          if (sizeInput && socialData.size) sizeInput.value = socialData.size;
        }
      });
    }

    if (state.dynamic && state.dynamic.staticSocial) {
      for (const [key, data] of Object.entries(state.dynamic.staticSocial)) {
        const input = document.getElementById(`input-${key}`);
        if (input) input.value = data.value || "";

        const placementRadio = document.querySelector(
          `input[name="placement-static-${key}"][value="${data.placement}"]`,
        );
        if (placementRadio) placementRadio.checked = true;
      }
    }

    if (state.imageUrls) {
      CardManager.frontBgImageUrl = state.imageUrls.front;
      CardManager.backBgImageUrl = state.imageUrls.back;
      CardManager.qrCodeImageUrl = state.imageUrls.qrCode;
      CardManager.personalPhotoUrl = state.imageUrls.photo;
      if (DOMElements.photoControls.url)
        DOMElements.photoControls.url.value = state.imageUrls.photo || "";

      DOMElements.buttons.removeFrontBg.style.display = state.imageUrls.front
        ? "block"
        : "none";
      DOMElements.buttons.removeBackBg.style.display = state.imageUrls.back
        ? "block"
        : "none";
    }

    if (state.placements) {
      for (const [elName, side] of Object.entries(state.placements)) {
        const radio = document.querySelector(
          `input[name="placement-${elName}"][value="${side}"]`,
        );
        if (radio) radio.checked = true;
      }
    }

    document.querySelectorAll("input, select, textarea").forEach((input) => {
      input.dispatchEvent(new Event("input", { bubbles: true }));
      input.dispatchEvent(new Event("change", { bubbles: true }));
    });

    if (state.positions) {
      for (const [id, pos] of Object.entries(state.positions)) {
        let elementId = id;
        if (
          id.startsWith("form-group-static-") &&
          !document.getElementById(id)
        ) {
          elementId = `social-link-static-${id.replace("form-group-static-", "")}`;
        }
        if (id.startsWith("dynsocial_") && !document.getElementById(id)) {
          elementId = `social-link-${id.replace(/[^a-zA-Z0-9-]/g, "-")}`;
        }

        const targetEl = document.getElementById(elementId);

        if (targetEl && pos) {
          targetEl.style.transform = `translate(${pos.x}px, ${pos.y}px)`;
          targetEl.setAttribute("data-x", pos.x);
          targetEl.setAttribute("data-y", pos.y);
        }
      }
    } else {
      DragManager.resetPositions();
    }

    if (state.inputs && state.inputs["theme-select-input"]) {
      UIManager.setActiveThumbnail(state.inputs["theme-select-input"]);
    }

    CardManager.renderCardContent();

    const qrSource = document.querySelector(
      'input[name="qr-source"]:checked',
    )?.value;
    if (qrSource === "auto-vcard") {
      setTimeout(() => CardManager.generateVCardQr(), 100);
    } else {
      CardManager.autoGeneratedQrDataUrl = null;
      CardManager.updateQrCodeDisplay();
    }

    CardManager.handleMasterSocialToggle();
    this.isApplyingState = false;

    if (!state.inputs || !state.inputs["layout-select-visual"]) {
      CardManager.applyLayout("classic");
    } else {
      CardManager.applyLayout(state.inputs["layout-select-visual"]);
    }
  },

  reset() {
    if (
      confirm(
        "هل أنت متأكد أنك تريد إعادة تعيين التصميم بالكامل؟ سيتم حذف أي بيانات محفوظة.",
      )
    ) {
      localStorage.removeItem(Config.LOCAL_STORAGE_KEY);
      window.location.reload();
    }
  },
  saveDebounced: Utils.debounce(() => {
    HistoryManager.pushState(StateManager.getStateObject());
    UIManager.showSaveNotification();
  }, 800),
};
